# For changes in dependencies
'📦 dependencies':
  - changed-files:
      - 'yarn.lock'

# For changes in documentation
'📖 documentation':
  - changed-files:
      - 'docs/*.md'
      - 'docs/**/*.md'
      - 'README.md'

# For changes in source code
'✨ enhancement':
  - changed-files:
      - 'src/*'

# For changes in site
'🌍 site':
  - changed-files:
      - 'public/*'
