name: 'coverage'
on:
  pull_request_target:
    branches:
      - main
      - development
      - utility
      - components
      - pages
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
